### ISSUE TITLE
Landscape-Umgebung für den FO-Auswertungsalgorithmus 

### ISSUE THREAD

**Issue by JKRhb** [th42sch/logikskript#1]
Abbildung 1 auf Seite 28 ließe sich meines Erachtens etwas konfortabler lesen und mit der Eingabe auf Seite 27 vergleichen, wenn man sie mithilfe des `pdflscape`-Paketes in eine `landscape`-Umgebung einbetten würde -- hierdurch wird die Seite im PDF automatisch gedreht und die Notwendigkeit, das tikz-Picture um 90 Grad zu drehen, entfiele ebenfalls.

**Comment by th42sch** [comment]
Danke für den Hinweis; wird mit nächstem Commit erledigt.
